version: '3.8'

services:
  chess-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_SOCKET_URL=ws://localhost:3000
      - NEXT_PUBLIC_KEEP_ALIVE_INTERVAL_MS=1000
